apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-resizer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sassenagh/node-image-resizer.git
    targetRevision: HEAD
    path: infrastructure/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: image-resizer-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: ""
      kind: Pod
      jsonPointers:
        - "/status"
